name: Publish Uclid Image

on:
    push:
        tags:
            - '[0-9]+.[0-9]+.[0-9]+'
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - name: Checkout the repository
            uses: actions/checkout@v4  
          - name: Log in to the Container registry
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build the Docker image
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: ${{ github.ref_name }}, latest
              github-token: ${{ secrets.GITHUB_TOKEN }}
              context: .
